---
repos:
  - repo: .
    rev: v0.1.0
    hooks:
      - id: cargo-fmt-nightly
        args:
          - --all
          - --
          - --config
          - unstable_features=true,group_imports=StdExternalCrate,imports_granularity=Item
      - id: cargo-check
        args: ["--locked"]
      - id: cargo-clippy
        args: ["--locked", "--all-targets", "--all-features"]
