[package]
name = "arista-pre-commit-hooks"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust-based pre-commit hooks for cargo workflows"
publish = false

[lib]
name = "arista_pre_commit_hooks"
path = "src/lib.rs"

[[bin]]
name = "cargo-fmt-hook"
path = "src/bin/cargo-fmt-hook.rs"

[[bin]]
name = "cargo-fmt-nightly-hook"
path = "src/bin/cargo-fmt-nightly-hook.rs"

[[bin]]
name = "cargo-check-hook"
path = "src/bin/cargo-check-hook.rs"

[[bin]]
name = "cargo-clippy-hook"
path = "src/bin/cargo-clippy-hook.rs"

[[bin]]
name = "cargo-deny-hook"
path = "src/bin/cargo-deny-hook.rs"

[[bin]]
name = "cargo-about-hook"
path = "src/bin/cargo-about-hook.rs"
